
find_package(x265 CONFIG QUIET)
if (x265_FOUND)
    message(STATUS "Found x265-${x265_VERSION} from ${x265_DIR}.")
else()
    find_path(X265_INCLUDE_DIR "x265.h" REQUIRED)
    if (WIN32)
        find_library(X265_LIBRARY_D "x265-static" HINTS ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib NO_DEFAULT_PATH NO_CMAKE_PATH)
        find_library(X265_LIBRARY_R "x265-static" HINTS ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib NO_DEFAULT_PATH NO_CMAKE_PATH)
    else()
        find_library(X265_LIBRARY_D "x265" HINTS ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib REQUIRED NO_DEFAULT_PATH NO_CMAKE_PATH)
        find_library(X265_LIBRARY_R "x265" HINTS ${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib REQUIRED NO_DEFAULT_PATH NO_CMAKE_PATH)
    endif()
    add_library(x265 INTERFACE)
    target_include_directories(x265 INTERFACE ${X265_INCLUDE_DIR})
    target_link_libraries(x265 INTERFACE debug ${X265_LIBRARY_D} optimized ${X265_LIBRARY_R})
endif()
